#!/bin/bash

# Requirements
# jq
# awscli 

WORKLOAD_ID="$1"
LENS_ALIAS="wellarchitected" # Currently, only the Well-Architected Framework is supported
AWS_PROFILE="$2"
AWS_REGION="$3"
PAGINATION=true
WORKLOAD_DATA=""
WORKLOADS_PILLARS=""

while $PAGINATION
do
    i=$(aws wellarchitected list-answers --workload-id "$WORKLOAD_ID" --lens-alias "$LENS_ALIAS" --profile "$AWS_PROFILE" --region "$AWS_REGION" --no-cli-pager --max-results 50 --next-token "$nextToken")

    WORKLOAD_DATA+=$(echo "$i" | jq -c '.')
    
    nextToken=$(echo "$i" | jq -r '.NextToken')

    if [ "$nextToken" == "null" ] || [ -z "$nextToken" ]; then
        echo "Retrieved all answers."
        PAGINATION=false 
    else
        echo "Fetching data..."
    fi
done
WORKLOADS_PILLARS=$(echo "$WORKLOAD_DATA" | jq -r '.AnswerSummaries[].PillarId' | sort | uniq)
for pillar in $WORKLOADS_PILLARS; do
    echo "Questions for Pillar: $pillar"
    echo "$WORKLOAD_DATA" | jq -r --arg pillar "$pillar" '
        .AnswerSummaries[] |
        select(.PillarId == $pillar) |
        .QuestionTitle'
    echo
done
